version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: golang_backend
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: library
      DB_SEED_PASSWORD: password123
    ports:
      - "8080:8080"

  # frontend:
  #   build: ./frontend
  #   container_name: nextjs_frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:3000"

volumes:
  db_data:
