SERVER:
  PORT: "8080"
  ENABLE_STACK_TRACE: true

CONNECTION:
  POSTGRES:
    HOST: "localhost"
    PORT: "5432"
    USERNAME: "admin"
    PASSWORD: "password"
    NAME: "library"

JWT:
  SECRET_KEY: "secret"
  EXP: 24